# Generated by Django 3.2.7 on 2021-09-16 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0002_auto_20210916_0154'),
    ]

    operations = [
        migrations.AddField(
            model_name='healthscore',
            name='created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
