# Generated by Django 3.2.7 on 2021-09-16 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0003_healthscore_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='healthscore',
            name='bmitext',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
