# Generated by Django 3.2.7 on 2021-09-16 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0004_healthscore_bmitext'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='healthscore',
            name='total',
        ),
        migrations.AddField(
            model_name='healthscore',
            name='bloodsugartext',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='healthscore',
            name='bptext',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='healthscore',
            name='cholesteroltext',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='healthscore',
            name='creatininetext',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='healthscore',
            name='bloodsugar',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='healthscore',
            name='cholesterol',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='healthscore',
            name='creatinine',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='healthscore',
            name='diabp',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='healthscore',
            name='sysbp',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
