# Generated by Django 3.2.7 on 2021-09-16 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0005_auto_20210916_1656'),
    ]

    operations = [
        migrations.AddField(
            model_name='healthscore',
            name='expired',
            field=models.DateTimeField(null=True),
        ),
    ]
