# Generated by Django 3.2.7 on 2021-09-16 20:14

import cloudinary.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tracker', '0006_healthscore_expired'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='healthscore',
            name='bloodsugartext',
        ),
        migrations.RemoveField(
            model_name='healthscore',
            name='bmitext',
        ),
        migrations.RemoveField(
            model_name='healthscore',
            name='bptext',
        ),
        migrations.RemoveField(
            model_name='healthscore',
            name='cholesteroltext',
        ),
        migrations.RemoveField(
            model_name='healthscore',
            name='creatininetext',
        ),
        migrations.RemoveField(
            model_name='healthscore',
            name='expired',
        ),
        migrations.AlterField(
            model_name='healthscore',
            name='bloodsugar',
            field=models.IntegerField(choices=[(1, 'Very Low'), (2, 'Low'), (3, 'Medium'), (2, 'High'), (1, 'Very High')], default=1),
        ),
        migrations.AlterField(
            model_name='healthscore',
            name='cholesterol',
            field=models.IntegerField(choices=[(1, 'Very Low'), (2, 'Low'), (3, 'Medium'), (2, 'High'), (1, 'Very High')], default=1),
        ),
        migrations.AlterField(
            model_name='healthscore',
            name='creatinine',
            field=models.IntegerField(choices=[(1, 'Very Low'), (2, 'Low'), (3, 'Medium'), (2, 'High'), (1, 'Very High')], default=1),
        ),
        migrations.AlterField(
            model_name='healthscore',
            name='diabp',
            field=models.IntegerField(choices=[(1, 'Very Low'), (2, 'Low'), (3, 'Medium'), (2, 'High'), (1, 'Very High')], default=1),
        ),
        migrations.AlterField(
            model_name='healthscore',
            name='sysbp',
            field=models.IntegerField(choices=[(1, 'Very Low'), (2, 'Low'), (3, 'Medium'), (2, 'High'), (1, 'Very High')], default=1),
        ),
        migrations.CreateModel(
            name='HealthReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pdf', cloudinary.models.CloudinaryField(max_length=255, verbose_name='pdf')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
